trigger_host[0]=A
trigger_host[startup]=trigger_host/trigger_host.startup

client_switch[0]=A
client_switch[1]=B
client_switch[image]=kathara/bmv2
client_switch[startup]=client_switch/client_switch.startup

server_switch[0]=B
server_switch[image]=kathara/bmv2
server_switch[startup]=server_switch/server_switch.startup
