trigger_host[0]="A"
trigger_host[image]="kathara/base"
trigger_host[startup]="trigger_host.startup"

client_switch[0]="A"
client_switch[1]="B"
client_switch[image]="kathara/p4"
client_switch[startup]="client_switch.startup"

server_switch[0]="B"
server_switch[image]="kathara/p4"
server_switch[startup]="server_switch.startup"
